### ISSUE TITLE
migration to buildroot 2022.02

### ISSUE THREAD

**Issue by jibanes** [afbjorklund/buildroot4kubernetes#18]
buildroot4kubernetes seems to work fine on buildroot-2022.02.x (stable); necessary changes:
genimage-bios.cfg: requires holes = {"(440; 512)"} in partition boot, as such:

```
  partition boot {
    in-partition-table = "no"
    image = "boot.img"
    offset = 0
    size = 512
    holes = {"(440; 512)"}
  }
```

I also recommend upgrading to the latest kernel, in buildroot_defconfig:
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="5.4.186"

**Comment by afbjorklund** [comment]
Thanks, will do

Juggling a couple of different builds, was contemplating UEFI - but I think I will leave these as BIOS (and RPi) for now...

Minikube has the other ISOs

**Comment by jibanes** [comment]
Thank you

**Comment by jibanes** [comment]
If time allows, maybe also upgrade to Go 1.18.

**Comment by afbjorklund** [comment]
At the moment, Kubernetes dictates the Go version used...

i.e. using the same go version as the official builds do

https://github.com/kubernetes/kubernetes/blob/v1.23.5/build/build-image/cross/VERSION

**Comment by jibanes** [comment]
Thanks, I didn't know there was such strong dependency.

**Comment by afbjorklund** [comment]
> Thanks, I didn't know there was such strong dependency.

There isn't, but easier to stay with the tested version ?

Unfortunately, they normally require latest/greatest go.
So doesn't always work, to stay with the system version.

But I think that Kubernetes 1.24 is currently using go1.18

**Comment by afbjorklund** [comment]
Updated to Buildroot 2022.02, ran into some cgroups v2 issues. :-(

* 87f932d84d0192c56a01a59e00d8d71f988f7f49

I think I found the missing config, but in my book it is still unstable...

* 3b1a8d058411732c89bcb0c12cdf659464b36485
